CREATE DATABASE GEART;
use GEART;

create table GEART(
CNPJ_GEART VARCHAR(20) NOT NULL,
NOME_GEART VARCHAR(35)NOT NULL,
PRIMARY KEY(CNPJ_GEART)
)default charset=utf8;

CREATE TABLE MENSALIDADE(
COD_MENS INT NOT NULL AUTO_INCREMENT,
MES_ANO_MENS VARCHAR(10) NOT NULL,
DATA_PAG_MENS  VARCHAR(10),
SITUACAO_MENS VARCHAR(10),
ATRASO_MENS VARCHAR(10),
RENOVACAO_MENS VARCHAR(10),
PRIMARY KEY (COD_MENS)
)default charset=utf8;



CREATE TABLE MEMBRO_JUVENIL(
REG_MEMBRO INT NOT NULL,
NOME_MEMBRO VARCHAR (45) NOT NULL,
RAMO_MEMBRO VARCHAR (20) NOT NULL,
PRIMARY KEY(REG_MEMBRO)
)default charset=utf8;

CREATE TABLE DIP(
COD_PT_DIP INT NOT NULL,
PT_MT_DIP  VARCHAR(15) NOT NULL,
ATIVIDADE_DIP VARCHAR(45)NOT NULL,
PONT_DIP INT NOT NULL,
PONT_GANHA_DIP INT NOT NULL,
DATA_DIP VARCHAR(20) NOT NULL,
BOLETIM VARCHAR(20),
CELULAR DOUBLE,
PALAVRAO DOUBLE,
MES VARCHAR(10),
PRIMARY KEY(COD_PT_DIP)
)default charset=utf8;

CREATE TABLE ALMOXARIFADO(
COD_MATERIAL INT NOT NULL AUTO_INCREMENT,
NOME_MATERIAL VARCHAR(20) NOT NULL,
EST_ATUAL_MATERIAL TEXT,
RAMO_MATERIAL VARCHAR(20) NOT NULL,
LOCAL_MATERIAL TEXT NOT NULL,
PRIMARY KEY(COD_MATERIAL)
)default charset=utf8;

CREATE TABLE ESCOTISTA(
REG_ESCOTISTA INT NOT NULL,
SENHA_ESCOTISTA VARCHAR(20) NOT NULL,
NOME_ESCOTISTA VARCHAR(30) NOT NULL,
CARGO_ESCOTISTA VARCHAR(15) NOT NULL,
RAMO_ESCOTISTA VARCHAR(15) NOT NULL,
PRIMARY KEY(REG_ESCOTISTA)
)default charset=utf8;

/*-----------RELACIONAMENTOS-----------*/

ALTER TABLE MEMBRO_JUVENIL
ADD COLUMN CNPJ_GEART VARCHAR(20);

ALTER TABLE MEMBRO_JUVENIL
ADD FOREIGN KEY (CNPJ_GEART)
REFERENCES GEART(CNPJ_GEART);

DESCRIBE MEMBRO_JUVENIL;

/*------------------------------------*/

ALTER TABLE MENSALIDADE
ADD COLUMN CNPJ_GEART VARCHAR(20);

ALTER TABLE MENSALIDADE
ADD FOREIGN KEY (CNPJ_GEART)
REFERENCES GEART(CNPJ_GEART);

DESCRIBE MENSALIDADE;

/*------------------------------------*/

ALTER TABLE ESCOTISTA
ADD COLUMN CNPJ_GEART VARCHAR(20);

ALTER TABLE ESCOTISTA
ADD FOREIGN KEY (CNPJ_GEART)
REFERENCES GEART(CNPJ_GEART);

DESCRIBE ESCOTISTA;

/*------------------------------------*/

ALTER TABLE GEART
ADD COLUMN COD_MATERIAL INT;

ALTER TABLE GEART
ADD FOREIGN KEY (COD_MATERIAL)
REFERENCES ALMOXARIFADO (COD_MATERIAL);

DESCRIBE GEART;

/*------------------------------------*/


ALTER TABLE ESCOTISTA
ADD COLUMN COD_PT_DIP INT;

ALTER TABLE ESCOTISTA
ADD FOREIGN KEY (COD_PT_DIP)
REFERENCES DIP (COD_PT_DIP);

DESCRIBE ESCOTISTA;

/*------------------------------------*/

